cc_library(
    name = "Nexg",
    srcs = ["src/Nexg.cpp"],
    hdrs = ["include/Nexg.h"],
    deps = ["//nexg/nexserver:NexServer","//nexg/nexgcore:NexgCore"],
    visibility = ["//nexg:__pkg__"],
)
